#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Bitirme_Projesi.Resource", IsApplication=true)]

namespace Bitirme_Projesi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int b = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int banner = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int adi = 2131099667;
			
			// aapt resource value: 0x7f06002d
			public const int adsoyad = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int adsyd = 2131099692;
			
			// aapt resource value: 0x7f06003c
			public const int alti = 2131099708;
			
			// aapt resource value: 0x7f06003b
			public const int bes = 2131099707;
			
			// aapt resource value: 0x7f060037
			public const int bir = 2131099703;
			
			// aapt resource value: 0x7f060019
			public const int blm = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int bolum = 2131099674;
			
			// aapt resource value: 0x7f06002e
			public const int bolumliste = 2131099694;
			
			// aapt resource value: 0x7f060017
			public const int d_adi = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int dadi = 2131099670;
			
			// aapt resource value: 0x7f060009
			public const int dgiris = 2131099657;
			
			// aapt resource value: 0x7f06002f
			public const int doktor = 2131099695;
			
			// aapt resource value: 0x7f060051
			public const int doktor_girisi = 2131099729;
			
			// aapt resource value: 0x7f060030
			public const int doktorliste = 2131099696;
			
			// aapt resource value: 0x7f06003f
			public const int dokuz = 2131099711;
			
			// aapt resource value: 0x7f06003a
			public const int dort = 2131099706;
			
			// aapt resource value: 0x7f060008
			public const int editText = 2131099656;
			
			// aapt resource value: 0x7f06004e
			public const int edttxt = 2131099726;
			
			// aapt resource value: 0x7f06000f
			public const int eeczane = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int h_adi = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int hasta = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int id = 2131099661;
			
			// aapt resource value: 0x7f060038
			public const int iki = 2131099704;
			
			// aapt resource value: 0x7f060023
			public const int ilac = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int ilc = 2131099682;
			
			// aapt resource value: 0x7f06002a
			public const int ileri = 2131099690;
			
			// aapt resource value: 0x7f060001
			public const int imageView = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int k_adi = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int kadi = 2131099651;
			
			// aapt resource value: 0x7f060024
			public const int kayit = 2131099684;
			
			// aapt resource value: 0x7f06000e
			public const int kod = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int linear_1 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int linear_2 = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int linear_3 = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int linear_4 = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int linear_5 = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int linear_6 = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int linear_7 = 2131099678;
			
			// aapt resource value: 0x7f060021
			public const int linear_8 = 2131099681;
			
			// aapt resource value: 0x7f060026
			public const int linear_hastalar = 2131099686;
			
			// aapt resource value: 0x7f060000
			public const int linear_res = 2131099648;
			
			// aapt resource value: 0x7f060036
			public const int linear_saatler = 2131099702;
			
			// aapt resource value: 0x7f060032
			public const int linear_tarih = 2131099698;
			
			// aapt resource value: 0x7f060028
			public const int linear_tarihsecim = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int listele = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int listetarih = 2131099689;
			
			// aapt resource value: 0x7f060040
			public const int on = 2131099712;
			
			// aapt resource value: 0x7f060046
			public const int onalti = 2131099718;
			
			// aapt resource value: 0x7f060045
			public const int onbes = 2131099717;
			
			// aapt resource value: 0x7f060041
			public const int onbir = 2131099713;
			
			// aapt resource value: 0x7f060049
			public const int ondokuz = 2131099721;
			
			// aapt resource value: 0x7f060044
			public const int ondort = 2131099716;
			
			// aapt resource value: 0x7f060042
			public const int oniki = 2131099714;
			
			// aapt resource value: 0x7f060048
			public const int onsekiz = 2131099720;
			
			// aapt resource value: 0x7f060043
			public const int onuc = 2131099715;
			
			// aapt resource value: 0x7f060047
			public const int onyedi = 2131099719;
			
			// aapt resource value: 0x7f060052
			public const int randevu_al = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int randevu_iptal = 2131099731;
			
			// aapt resource value: 0x7f060033
			public const int randevutarih = 2131099699;
			
			// aapt resource value: 0x7f06000a
			public const int relative1 = 2131099658;
			
			// aapt resource value: 0x7f060050
			public const int riptal = 2131099728;
			
			// aapt resource value: 0x7f06004f
			public const int rndval = 2131099727;
			
			// aapt resource value: 0x7f060031
			public const int rndvtrh = 2131099697;
			
			// aapt resource value: 0x7f060035
			public const int saat = 2131099701;
			
			// aapt resource value: 0x7f06003e
			public const int sekiz = 2131099710;
			
			// aapt resource value: 0x7f060006
			public const int sfr = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int sifre = 2131099655;
			
			// aapt resource value: 0x7f06001d
			public const int sikayet = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int skyt = 2131099676;
			
			// aapt resource value: 0x7f060020
			public const int tani = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int tani_ = 2131099679;
			
			// aapt resource value: 0x7f060025
			public const int tarih = 2131099685;
			
			// aapt resource value: 0x7f06000c
			public const int tc = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int tc_k = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int tckimlik = 2131099659;
			
			// aapt resource value: 0x7f06002b
			public const int tckimlikno = 2131099691;
			
			// aapt resource value: 0x7f060034
			public const int textView = 2131099700;
			
			// aapt resource value: 0x7f060039
			public const int uc = 2131099705;
			
			// aapt resource value: 0x7f06003d
			public const int yedi = 2131099709;
			
			// aapt resource value: 0x7f06004a
			public const int yirmi = 2131099722;
			
			// aapt resource value: 0x7f06004d
			public const int yirmidort = 2131099725;
			
			// aapt resource value: 0x7f06004b
			public const int yirmiiki = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int yirmiuc = 2131099724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int doktor_girisi = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int eeczane = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hasta = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hasta_listesi = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ilac_listesi = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ilkgiris = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int randevu_al = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int randevu_sil = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int ad = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int blm = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int doktor = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int saat = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int sikayet = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int tarih = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int tc = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
