//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Bitirme_Projesi.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ITestService", Namespace="http://tempuri.org/")]
    public partial class TestService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DoktorGirisiOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoktorAdiniGetirOperationCompleted;
        
        private System.Threading.SendOrPostCallback HastaIsimOperationCompleted;
        
        private System.Threading.SendOrPostCallback EeczaneGirisiOperationCompleted;
        
        private System.Threading.SendOrPostCallback RandevuSilmeOperationCompleted;
        
        private System.Threading.SendOrPostCallback HastaBilgileriOperationCompleted;
        
        private System.Threading.SendOrPostCallback BolumListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoktorListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback BolumYazdirmaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SikayetYazdirmaOperationCompleted;
        
        private System.Threading.SendOrPostCallback HastaTcOperationCompleted;
        
        private System.Threading.SendOrPostCallback RandevuAlOperationCompleted;
        
        private System.Threading.SendOrPostCallback IlacKaydiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TestService() {
            this.Url = "http://192.168.1.16/service.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DoktorGirisiCompletedEventHandler DoktorGirisiCompleted;
        
        /// <remarks/>
        public event DoktorAdiniGetirCompletedEventHandler DoktorAdiniGetirCompleted;
        
        /// <remarks/>
        public event HastaIsimCompletedEventHandler HastaIsimCompleted;
        
        /// <remarks/>
        public event EeczaneGirisiCompletedEventHandler EeczaneGirisiCompleted;
        
        /// <remarks/>
        public event RandevuSilmeCompletedEventHandler RandevuSilmeCompleted;
        
        /// <remarks/>
        public event HastaBilgileriCompletedEventHandler HastaBilgileriCompleted;
        
        /// <remarks/>
        public event BolumListesiCompletedEventHandler BolumListesiCompleted;
        
        /// <remarks/>
        public event DoktorListesiCompletedEventHandler DoktorListesiCompleted;
        
        /// <remarks/>
        public event BolumYazdirmaCompletedEventHandler BolumYazdirmaCompleted;
        
        /// <remarks/>
        public event SikayetYazdirmaCompletedEventHandler SikayetYazdirmaCompleted;
        
        /// <remarks/>
        public event HastaTcCompletedEventHandler HastaTcCompleted;
        
        /// <remarks/>
        public event RandevuAlCompletedEventHandler RandevuAlCompleted;
        
        /// <remarks/>
        public event IlacKaydiCompletedEventHandler IlacKaydiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/DoktorGirisi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DoktorGirisi([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string k_adi, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sifre) {
            object[] results = this.Invoke("DoktorGirisi", new object[] {
                        k_adi,
                        sifre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DoktorGirisiAsync(string k_adi, string sifre) {
            this.DoktorGirisiAsync(k_adi, sifre, null);
        }
        
        /// <remarks/>
        public void DoktorGirisiAsync(string k_adi, string sifre, object userState) {
            if ((this.DoktorGirisiOperationCompleted == null)) {
                this.DoktorGirisiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoktorGirisiOperationCompleted);
            }
            this.InvokeAsync("DoktorGirisi", new object[] {
                        k_adi,
                        sifre}, this.DoktorGirisiOperationCompleted, userState);
        }
        
        private void OnDoktorGirisiOperationCompleted(object arg) {
            if ((this.DoktorGirisiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoktorGirisiCompleted(this, new DoktorGirisiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/DoktorAdiniGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DoktorAdiniGetir([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string k_adi) {
            object[] results = this.Invoke("DoktorAdiniGetir", new object[] {
                        k_adi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DoktorAdiniGetirAsync(string k_adi) {
            this.DoktorAdiniGetirAsync(k_adi, null);
        }
        
        /// <remarks/>
        public void DoktorAdiniGetirAsync(string k_adi, object userState) {
            if ((this.DoktorAdiniGetirOperationCompleted == null)) {
                this.DoktorAdiniGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoktorAdiniGetirOperationCompleted);
            }
            this.InvokeAsync("DoktorAdiniGetir", new object[] {
                        k_adi}, this.DoktorAdiniGetirOperationCompleted, userState);
        }
        
        private void OnDoktorAdiniGetirOperationCompleted(object arg) {
            if ((this.DoktorAdiniGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoktorAdiniGetirCompleted(this, new DoktorAdiniGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/HastaIsim", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HastaIsim([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string doktor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string randevu_tarihi) {
            object[] results = this.Invoke("HastaIsim", new object[] {
                        doktor,
                        randevu_tarihi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HastaIsimAsync(string doktor, string randevu_tarihi) {
            this.HastaIsimAsync(doktor, randevu_tarihi, null);
        }
        
        /// <remarks/>
        public void HastaIsimAsync(string doktor, string randevu_tarihi, object userState) {
            if ((this.HastaIsimOperationCompleted == null)) {
                this.HastaIsimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHastaIsimOperationCompleted);
            }
            this.InvokeAsync("HastaIsim", new object[] {
                        doktor,
                        randevu_tarihi}, this.HastaIsimOperationCompleted, userState);
        }
        
        private void OnHastaIsimOperationCompleted(object arg) {
            if ((this.HastaIsimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HastaIsimCompleted(this, new HastaIsimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/EeczaneGirisi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EeczaneGirisi(int tc_kimlik, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tc_kimlikSpecified, int kod, [System.Xml.Serialization.XmlIgnoreAttribute()] bool kodSpecified) {
            object[] results = this.Invoke("EeczaneGirisi", new object[] {
                        tc_kimlik,
                        tc_kimlikSpecified,
                        kod,
                        kodSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EeczaneGirisiAsync(int tc_kimlik, bool tc_kimlikSpecified, int kod, bool kodSpecified) {
            this.EeczaneGirisiAsync(tc_kimlik, tc_kimlikSpecified, kod, kodSpecified, null);
        }
        
        /// <remarks/>
        public void EeczaneGirisiAsync(int tc_kimlik, bool tc_kimlikSpecified, int kod, bool kodSpecified, object userState) {
            if ((this.EeczaneGirisiOperationCompleted == null)) {
                this.EeczaneGirisiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEeczaneGirisiOperationCompleted);
            }
            this.InvokeAsync("EeczaneGirisi", new object[] {
                        tc_kimlik,
                        tc_kimlikSpecified,
                        kod,
                        kodSpecified}, this.EeczaneGirisiOperationCompleted, userState);
        }
        
        private void OnEeczaneGirisiOperationCompleted(object arg) {
            if ((this.EeczaneGirisiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EeczaneGirisiCompleted(this, new EeczaneGirisiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/RandevuSilme", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RandevuSilme(int tc_k, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tc_kSpecified, int kod_k, [System.Xml.Serialization.XmlIgnoreAttribute()] bool kod_kSpecified) {
            object[] results = this.Invoke("RandevuSilme", new object[] {
                        tc_k,
                        tc_kSpecified,
                        kod_k,
                        kod_kSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RandevuSilmeAsync(int tc_k, bool tc_kSpecified, int kod_k, bool kod_kSpecified) {
            this.RandevuSilmeAsync(tc_k, tc_kSpecified, kod_k, kod_kSpecified, null);
        }
        
        /// <remarks/>
        public void RandevuSilmeAsync(int tc_k, bool tc_kSpecified, int kod_k, bool kod_kSpecified, object userState) {
            if ((this.RandevuSilmeOperationCompleted == null)) {
                this.RandevuSilmeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRandevuSilmeOperationCompleted);
            }
            this.InvokeAsync("RandevuSilme", new object[] {
                        tc_k,
                        tc_kSpecified,
                        kod_k,
                        kod_kSpecified}, this.RandevuSilmeOperationCompleted, userState);
        }
        
        private void OnRandevuSilmeOperationCompleted(object arg) {
            if ((this.RandevuSilmeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RandevuSilmeCompleted(this, new RandevuSilmeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/HastaBilgileri", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HastaBilgileri(int tc_k, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tc_kSpecified) {
            object[] results = this.Invoke("HastaBilgileri", new object[] {
                        tc_k,
                        tc_kSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HastaBilgileriAsync(int tc_k, bool tc_kSpecified) {
            this.HastaBilgileriAsync(tc_k, tc_kSpecified, null);
        }
        
        /// <remarks/>
        public void HastaBilgileriAsync(int tc_k, bool tc_kSpecified, object userState) {
            if ((this.HastaBilgileriOperationCompleted == null)) {
                this.HastaBilgileriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHastaBilgileriOperationCompleted);
            }
            this.InvokeAsync("HastaBilgileri", new object[] {
                        tc_k,
                        tc_kSpecified}, this.HastaBilgileriOperationCompleted, userState);
        }
        
        private void OnHastaBilgileriOperationCompleted(object arg) {
            if ((this.HastaBilgileriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HastaBilgileriCompleted(this, new HastaBilgileriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/BolumListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BolumListesi() {
            object[] results = this.Invoke("BolumListesi", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BolumListesiAsync() {
            this.BolumListesiAsync(null);
        }
        
        /// <remarks/>
        public void BolumListesiAsync(object userState) {
            if ((this.BolumListesiOperationCompleted == null)) {
                this.BolumListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBolumListesiOperationCompleted);
            }
            this.InvokeAsync("BolumListesi", new object[0], this.BolumListesiOperationCompleted, userState);
        }
        
        private void OnBolumListesiOperationCompleted(object arg) {
            if ((this.BolumListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BolumListesiCompleted(this, new BolumListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/DoktorListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DoktorListesi([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bolumu) {
            object[] results = this.Invoke("DoktorListesi", new object[] {
                        bolumu});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DoktorListesiAsync(string bolumu) {
            this.DoktorListesiAsync(bolumu, null);
        }
        
        /// <remarks/>
        public void DoktorListesiAsync(string bolumu, object userState) {
            if ((this.DoktorListesiOperationCompleted == null)) {
                this.DoktorListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoktorListesiOperationCompleted);
            }
            this.InvokeAsync("DoktorListesi", new object[] {
                        bolumu}, this.DoktorListesiOperationCompleted, userState);
        }
        
        private void OnDoktorListesiOperationCompleted(object arg) {
            if ((this.DoktorListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoktorListesiCompleted(this, new DoktorListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/BolumYazdirma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BolumYazdirma([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string adisoyadi) {
            object[] results = this.Invoke("BolumYazdirma", new object[] {
                        adisoyadi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BolumYazdirmaAsync(string adisoyadi) {
            this.BolumYazdirmaAsync(adisoyadi, null);
        }
        
        /// <remarks/>
        public void BolumYazdirmaAsync(string adisoyadi, object userState) {
            if ((this.BolumYazdirmaOperationCompleted == null)) {
                this.BolumYazdirmaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBolumYazdirmaOperationCompleted);
            }
            this.InvokeAsync("BolumYazdirma", new object[] {
                        adisoyadi}, this.BolumYazdirmaOperationCompleted, userState);
        }
        
        private void OnBolumYazdirmaOperationCompleted(object arg) {
            if ((this.BolumYazdirmaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BolumYazdirmaCompleted(this, new BolumYazdirmaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/SikayetYazdirma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SikayetYazdirma([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string adisoyadi, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string doktor) {
            object[] results = this.Invoke("SikayetYazdirma", new object[] {
                        adisoyadi,
                        doktor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SikayetYazdirmaAsync(string adisoyadi, string doktor) {
            this.SikayetYazdirmaAsync(adisoyadi, doktor, null);
        }
        
        /// <remarks/>
        public void SikayetYazdirmaAsync(string adisoyadi, string doktor, object userState) {
            if ((this.SikayetYazdirmaOperationCompleted == null)) {
                this.SikayetYazdirmaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSikayetYazdirmaOperationCompleted);
            }
            this.InvokeAsync("SikayetYazdirma", new object[] {
                        adisoyadi,
                        doktor}, this.SikayetYazdirmaOperationCompleted, userState);
        }
        
        private void OnSikayetYazdirmaOperationCompleted(object arg) {
            if ((this.SikayetYazdirmaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SikayetYazdirmaCompleted(this, new SikayetYazdirmaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/HastaTc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HastaTc([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string adisoyadi) {
            object[] results = this.Invoke("HastaTc", new object[] {
                        adisoyadi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HastaTcAsync(string adisoyadi) {
            this.HastaTcAsync(adisoyadi, null);
        }
        
        /// <remarks/>
        public void HastaTcAsync(string adisoyadi, object userState) {
            if ((this.HastaTcOperationCompleted == null)) {
                this.HastaTcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHastaTcOperationCompleted);
            }
            this.InvokeAsync("HastaTc", new object[] {
                        adisoyadi}, this.HastaTcOperationCompleted, userState);
        }
        
        private void OnHastaTcOperationCompleted(object arg) {
            if ((this.HastaTcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HastaTcCompleted(this, new HastaTcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/RandevuAl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RandevuAl([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tc_kimlik, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string adsoyad, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bolum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string doktor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string randevu_tarihi, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string randevu_saati, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sikayet) {
            object[] results = this.Invoke("RandevuAl", new object[] {
                        tc_kimlik,
                        adsoyad,
                        bolum,
                        doktor,
                        randevu_tarihi,
                        randevu_saati,
                        sikayet});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RandevuAlAsync(string tc_kimlik, string adsoyad, string bolum, string doktor, string randevu_tarihi, string randevu_saati, string sikayet) {
            this.RandevuAlAsync(tc_kimlik, adsoyad, bolum, doktor, randevu_tarihi, randevu_saati, sikayet, null);
        }
        
        /// <remarks/>
        public void RandevuAlAsync(string tc_kimlik, string adsoyad, string bolum, string doktor, string randevu_tarihi, string randevu_saati, string sikayet, object userState) {
            if ((this.RandevuAlOperationCompleted == null)) {
                this.RandevuAlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRandevuAlOperationCompleted);
            }
            this.InvokeAsync("RandevuAl", new object[] {
                        tc_kimlik,
                        adsoyad,
                        bolum,
                        doktor,
                        randevu_tarihi,
                        randevu_saati,
                        sikayet}, this.RandevuAlOperationCompleted, userState);
        }
        
        private void OnRandevuAlOperationCompleted(object arg) {
            if ((this.RandevuAlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RandevuAlCompleted(this, new RandevuAlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITestService/IlacKaydi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IlacKaydi(int tc_kimlik, [System.Xml.Serialization.XmlIgnoreAttribute()] bool tc_kimlikSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string adisoyadi, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string doktoradi, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bolum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sikayet, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tani, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string k_ilaclar) {
            object[] results = this.Invoke("IlacKaydi", new object[] {
                        tc_kimlik,
                        tc_kimlikSpecified,
                        adisoyadi,
                        doktoradi,
                        bolum,
                        sikayet,
                        tani,
                        k_ilaclar});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IlacKaydiAsync(int tc_kimlik, bool tc_kimlikSpecified, string adisoyadi, string doktoradi, string bolum, string sikayet, string tani, string k_ilaclar) {
            this.IlacKaydiAsync(tc_kimlik, tc_kimlikSpecified, adisoyadi, doktoradi, bolum, sikayet, tani, k_ilaclar, null);
        }
        
        /// <remarks/>
        public void IlacKaydiAsync(int tc_kimlik, bool tc_kimlikSpecified, string adisoyadi, string doktoradi, string bolum, string sikayet, string tani, string k_ilaclar, object userState) {
            if ((this.IlacKaydiOperationCompleted == null)) {
                this.IlacKaydiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIlacKaydiOperationCompleted);
            }
            this.InvokeAsync("IlacKaydi", new object[] {
                        tc_kimlik,
                        tc_kimlikSpecified,
                        adisoyadi,
                        doktoradi,
                        bolum,
                        sikayet,
                        tani,
                        k_ilaclar}, this.IlacKaydiOperationCompleted, userState);
        }
        
        private void OnIlacKaydiOperationCompleted(object arg) {
            if ((this.IlacKaydiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IlacKaydiCompleted(this, new IlacKaydiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DoktorGirisiCompletedEventHandler(object sender, DoktorGirisiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoktorGirisiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoktorGirisiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DoktorAdiniGetirCompletedEventHandler(object sender, DoktorAdiniGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoktorAdiniGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoktorAdiniGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HastaIsimCompletedEventHandler(object sender, HastaIsimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HastaIsimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HastaIsimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void EeczaneGirisiCompletedEventHandler(object sender, EeczaneGirisiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EeczaneGirisiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EeczaneGirisiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RandevuSilmeCompletedEventHandler(object sender, RandevuSilmeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RandevuSilmeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RandevuSilmeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HastaBilgileriCompletedEventHandler(object sender, HastaBilgileriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HastaBilgileriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HastaBilgileriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void BolumListesiCompletedEventHandler(object sender, BolumListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BolumListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BolumListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DoktorListesiCompletedEventHandler(object sender, DoktorListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoktorListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoktorListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void BolumYazdirmaCompletedEventHandler(object sender, BolumYazdirmaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BolumYazdirmaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BolumYazdirmaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SikayetYazdirmaCompletedEventHandler(object sender, SikayetYazdirmaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SikayetYazdirmaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SikayetYazdirmaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HastaTcCompletedEventHandler(object sender, HastaTcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HastaTcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HastaTcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RandevuAlCompletedEventHandler(object sender, RandevuAlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RandevuAlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RandevuAlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void IlacKaydiCompletedEventHandler(object sender, IlacKaydiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IlacKaydiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IlacKaydiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591